# Site settings
title: XAXXJS | Ciberseguridad
description: Soy un entusiasta de la programación y ciberseguridad.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: xaxxjs
user_description: Me gusta la ciberseguridad y programación. Podrás ver algunos de mis proyectos personales y certificados.
user_title: Software Developer | Ciberseguridad
email: anon@anon.com
twitter_username: xaxxjs
github_username:  sergioab7
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
